/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Empleos.InsertarEmpleo;
import Empleos.ModificarEmpleo;
import gestores.GestorEmpleos;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Brito, Dennis Bonilla y Sebastián Palate
 */
public class Ofertante extends javax.swing.JFrame {

    private final InsertarEmpleo ie = new InsertarEmpleo();
    public static Integer fila;
    public static String identificacion;
    private final ModificarEmpleo me = new ModificarEmpleo();

    /**
     * Creates new form Ofertante
     */
    public Ofertante() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarDatosEmpleos();
        seleccionarEmpleo();
        obtenerEmpleo();
    }

    public static void cargarDatosEmpleos() {
        DefaultTableModel modeloTabla = GestorEmpleos.mostrarEmpleos(Login.ced_login);
        if (modeloTabla != null) {
            jtblEmpleos.setModel(modeloTabla);
        } else {
            JOptionPane.showMessageDialog(null, "Error en la Tabla");
        }
    }

    public void seleccionarEmpleo() {
        jtblEmpleos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jtblEmpleos.getSelectedRow() != -1) {
                    fila = jtblEmpleos.getSelectedRow();
                    identificacion = (String) jtblEmpleos.getValueAt(fila, 0);
                }
            }
        });
    }
    
    public void obtenerEmpleo() {
        jtblEmpleos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jtblEmpleos.getSelectedRow() != -1) {                                       
                    fila = jtblEmpleos.getSelectedRow();
                    ModificarEmpleo.jtxtNombre.setText(jtblEmpleos.getValueAt(fila, 1).toString());
                    ModificarEmpleo.jtxaDescripcion.setText(jtblEmpleos.getValueAt(fila, 2).toString());
                    ModificarEmpleo.jtxtPrecioMinimo.setText(jtblEmpleos.getValueAt(fila, 3).toString());
                    ModificarEmpleo.jtxtPrecioMaximo.setText(jtblEmpleos.getValueAt(fila, 4).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnPublicarEmpleo = new javax.swing.JButton();
        jbtnEliminarEmpleo = new javax.swing.JButton();
        jbtnModificarEmpleo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEmpleos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnPublicarEmpleo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPublicarEmpleo.setText("Publicar Empleo");
        jbtnPublicarEmpleo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPublicarEmpleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPublicarEmpleoActionPerformed(evt);
            }
        });

        jbtnEliminarEmpleo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnEliminarEmpleo.setText("Eliminar un Empleo");
        jbtnEliminarEmpleo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEliminarEmpleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarEmpleoActionPerformed(evt);
            }
        });

        jbtnModificarEmpleo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnModificarEmpleo.setText("Modificar un Empleo");
        jbtnModificarEmpleo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnModificarEmpleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarEmpleoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Empleos Publicados ");

        jtblEmpleos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblEmpleos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnModificarEmpleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnEliminarEmpleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPublicarEmpleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnPublicarEmpleo)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnEliminarEmpleo)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnModificarEmpleo)
                        .addGap(21, 21, 21))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPublicarEmpleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPublicarEmpleoActionPerformed
        if (!ie.isVisible()) {
            ie.setVisible(true);          
        }
        //cargarDatosEmpleos();
    }//GEN-LAST:event_jbtnPublicarEmpleoActionPerformed

    private void jbtnEliminarEmpleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarEmpleoActionPerformed
        GestorEmpleos.eliminarEmpleo();
        cargarDatosEmpleos();
    }//GEN-LAST:event_jbtnEliminarEmpleoActionPerformed

    private void jbtnModificarEmpleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarEmpleoActionPerformed
        obtenerEmpleo();
        if (!me.isVisible()) {
            me.setVisible(true);
        }
        
    }//GEN-LAST:event_jbtnModificarEmpleoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ofertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ofertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ofertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ofertante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ofertante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEliminarEmpleo;
    private javax.swing.JButton jbtnModificarEmpleo;
    private javax.swing.JButton jbtnPublicarEmpleo;
    public static javax.swing.JTable jtblEmpleos;
    // End of variables declaration//GEN-END:variables
}
